name: Run ShellCheck

author: Benjamin Wuethrich

description: Run ShellCheck on all shell files

branding:
  icon: terminal
  color: green

runs:
  using: composite
  steps:
    - name: Install ShellCheck
      shell: bash
      env:
        # yamllint disable-line rule:line-length
        SC_URL: https://github.com/koalaman/shellcheck/releases/download/v0.8.0/shellcheck-v0.8.0.linux.x86_64.tar.xz
      run: |
        echo "Installing ShellCheck..." >&2
          mkdir --parents "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"
          curl --silent --location "$SC_URL" \
              | tar --extract --xz --directory="$HOME/.local/bin" \
                  --strip-components=1 shellcheck-v0.8.0/shellcheck
          shellcheck --version >&2

    - name: Run ShellCheck
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH/runshellcheck"
