name: Lint code base

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:

  super-linter:
    name: Lint code base
    runs-on: ubuntu-20.04
    steps:

      - name: Check out repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter/slim@v4.8.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: true

          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_DOCKERFILE: true
          VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JSCPD: true
          VALIDATE_MARKDOWN: true
          VALIDATE_SHELL_SHFMT: true
          VALIDATE_YAML: true

  shellcheck:
    name: Run shellcheck
    runs-on: ubuntu-20.04
    steps:

      - name: Check out code
        uses: actions/checkout@v2.4.0

      - name: Run shellcheck
        uses: bewuethr/shellcheck-action@v2
